In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/kaggle/input/resume-dataset/gpt_dataset.csv")

In [3]:
z1=df['Category'].unique()

In [4]:
df['Category'].value_counts()

Category
Backend Developer                     57
Cloud Engineer                        56
Frontend Developer                    54
Data Scientist                        53
Full Stack Developer                  47
Python Developer                      45
Mobile App Developer (iOS/Android)    45
Machine Learning Engineer             43
Name: count, dtype: int64

In [5]:
df.isnull().sum()

Category    0
Resume      0
dtype: int64

In [6]:
df.duplicated().sum()

212

In [7]:
print(df)

                 Category                                             Resume
0      Frontend Developer  As a seasoned Frontend Developer, I have a pro...
1       Backend Developer  With a solid background in Backend Development...
2        Python Developer  As a Python Developer, I leverage my expertise...
3          Data Scientist  With a background in Data Science, I possess a...
4      Frontend Developer  Experienced Frontend Developer with a passion ...
..                    ...                                                ...
395        Cloud Engineer  Dynamic Cloud Engineer specializing in archite...
396        Cloud Engineer  Skilled Cloud Engineer with a focus on buildin...
397  Full Stack Developer  Experienced Full Stack Developer with expertis...
398  Full Stack Developer  Innovative Full Stack Developer with a passion...
399  Full Stack Developer  Dynamic Full Stack Developer specializing in b...

[400 rows x 2 columns]


# Lowercasing

In [8]:
df['Resume']=df['Resume'].apply(lambda x:x.lower())

In [9]:
df

Category                                             Resume
0      Frontend Developer  as a seasoned frontend developer, i have a pro...
1       Backend Developer  with a solid background in backend development...
2        Python Developer  as a python developer, i leverage my expertise...
3          Data Scientist  with a background in data science, i possess a...
4      Frontend Developer  experienced frontend developer with a passion ...
..                    ...                                                ...
395        Cloud Engineer  dynamic cloud engineer specializing in archite...
396        Cloud Engineer  skilled cloud engineer with a focus on buildin...
397  Full Stack Developer  experienced full stack developer with expertis...
398  Full Stack Developer  innovative full stack developer with a passion...
399  Full Stack Developer  dynamic full stack developer specializing in b...

[400 rows x 2 columns]

# Removing Stopwords

In [10]:
from nltk.corpus import stopwords
sw_list=stopwords.words('english')

In [11]:
df['Resume']=df['Resume'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [12]:
df

Category                                             Resume
0      Frontend Developer  seasoned frontend developer, proven track reco...
1       Backend Developer  solid background backend development, bring 7 ...
2        Python Developer  python developer, leverage expertise python pr...
3          Data Scientist  background data science, possess unique blend ...
4      Frontend Developer  experienced frontend developer passion craftin...
..                    ...                                                ...
395        Cloud Engineer  dynamic cloud engineer specializing architecti...
396        Cloud Engineer  skilled cloud engineer focus building secure s...
397  Full Stack Developer  experienced full stack developer expertise dev...
398  Full Stack Developer  innovative full stack developer passion buildi...
399  Full Stack Developer  dynamic full stack developer specializing buil...

[400 rows x 2 columns]

# Removing Numbers

In [13]:
df['Resume']=df['Resume'].apply(lambda x:' '.join([i for i in x.split() if not i.isdigit()]))

In [14]:
df

Category                                             Resume
0      Frontend Developer  seasoned frontend developer, proven track reco...
1       Backend Developer  solid background backend development, bring ye...
2        Python Developer  python developer, leverage expertise python pr...
3          Data Scientist  background data science, possess unique blend ...
4      Frontend Developer  experienced frontend developer passion craftin...
..                    ...                                                ...
395        Cloud Engineer  dynamic cloud engineer specializing architecti...
396        Cloud Engineer  skilled cloud engineer focus building secure s...
397  Full Stack Developer  experienced full stack developer expertise dev...
398  Full Stack Developer  innovative full stack developer passion buildi...
399  Full Stack Developer  dynamic full stack developer specializing buil...

[400 rows x 2 columns]

# Removing Punctuation

In [15]:
import string
PUNCT_TO_REMOVE = string.punctuation
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', PUNCT_TO_REMOVE))

In [16]:
df['Resume']=df['Resume'].apply(remove_punctuation)

In [17]:
df

Category                                             Resume
0      Frontend Developer  seasoned frontend developer proven track recor...
1       Backend Developer  solid background backend development bring yea...
2        Python Developer  python developer leverage expertise python pro...
3          Data Scientist  background data science possess unique blend a...
4      Frontend Developer  experienced frontend developer passion craftin...
..                    ...                                                ...
395        Cloud Engineer  dynamic cloud engineer specializing architecti...
396        Cloud Engineer  skilled cloud engineer focus building secure s...
397  Full Stack Developer  experienced full stack developer expertise dev...
398  Full Stack Developer  innovative full stack developer passion buildi...
399  Full Stack Developer  dynamic full stack developer specializing buil...

[400 rows x 2 columns]

In [18]:
x=df.drop(columns='Category')

In [19]:
y=df['Category']

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
y=LabelEncoder().fit_transform(y)

In [22]:
y

array([3, 0, 7, 2, 3, 3, 0, 0, 7, 7, 2, 2, 3, 0, 7, 2, 2, 3, 0, 7, 2, 2,
       3, 0, 7, 2, 2, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
       7, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [25]:
z2=df2[0].unique()

In [24]:
df2=pd.DataFrame(y)

In [26]:
dict={}
for i in range(len(z2)):
    dict[z2[i]]=z1[i]

In [27]:
dict

{3: 'Frontend Developer',
 0: 'Backend Developer',
 7: 'Python Developer',
 2: 'Data Scientist',
 4: 'Full Stack Developer',
 6: 'Mobile App Developer (iOS/Android)',
 5: 'Machine Learning Engineer',
 1: 'Cloud Engineer'}

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3,stratify=y)

In [29]:
print(x_train.shape,x_test.shape)

(320, 1) (80, 1)


In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [31]:
tfidf=TfidfVectorizer()

In [32]:
x_train=tfidf.fit_transform(x_train['Resume']).toarray()
x_test=tfidf.transform(x_test['Resume'])

In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix

In [34]:
rf=RandomForestClassifier()
rf.fit(x_train,y_train)
y_pred=rf.predict(x_test)
accuracy_score(y_test,y_pred)

1.0

In [35]:
y_pred

array([6, 0, 3, 3, 4, 7, 0, 3, 0, 2, 3, 6, 3, 1, 1, 0, 0, 2, 2, 0, 1, 3,
       4, 7, 4, 2, 3, 7, 0, 2, 5, 5, 1, 2, 2, 5, 6, 4, 6, 5, 3, 6, 6, 4,
       4, 5, 4, 1, 0, 3, 7, 1, 2, 2, 1, 0, 1, 4, 7, 6, 6, 2, 1, 7, 0, 7,
       5, 6, 3, 5, 1, 4, 7, 2, 3, 1, 7, 5, 5, 0])

In [36]:
confusion_matrix(y_test,y_pred)

array([[11,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 11,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  9,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  9,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  9]])

In [37]:
import pickle
model_pkl_file = "resumeclassifier.pkl"  

with open(model_pkl_file, 'wb') as file:  
    pickle.dump(rf, file)

In [38]:
with open(model_pkl_file, 'rb') as file:  
    rf = pickle.load(file)
y_pred=rf.predict(x_test)
accuracy_score(y_test,y_pred)

1.0

In [39]:
model_pkl_file = "tfidf.pkl"  

with open(model_pkl_file, 'wb') as file:  
    pickle.dump(tfidf, file)